### ISSUE TITLE
Boost Lion Support

### ISSUE THREAD

**Issue by bored-engineer** [msftguy/ssh-rd#1]
The version of boost included does not appear to compile on OS X Lion.

Running build-osx.sh yeild the following error:

```
error: "10.7" is not a known value of feature <macosx-version>
error: legal values:
```

**Comment by msftguy** [comment]
It seems related to a Boost bug with XCode 4.3: https://svn.boost.org/trac/boost/ticket/6686
Just drop 'macosx-version=10.7 macosx-version-min=10.6' from the script; it should build fine after that..
Please reopen if that doesn't solve the problem..
