### ISSUE TITLE
iPhone 4 - Maxconnect

### ISSUE THREAD

**Issue by johnkodes** [msftguy/ssh-rd#3]
I have tried everything but I can't boot my phone (almost same issue as this http://www.jailbreakqa.com/questions/102987/iphone-4-unknown-ios-stuck-in-apple-logo-loop), I can specificaly describe it later. I tried your smart program :), because I really don't know what else to do. So I ran the program but it fails at the "Almost there" step. After this step the iPhone should connect in MaxConnect state if I'm not mistaken, but my iPhone only works in Recovery or DFU mode. If you have any advice for me, I would be so so thankful else there's hammer waiting for my iFriend. :(. Thank you very much.

**Comment by markcoker** [comment]
go to www.jailbreakqa.com for questions

have you tried tinyumbrella fix recovery loop? worst case just restore.

sigh, just looked at the date a year ago.
